# Form implementation generated from reading ui file 'giaodien.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 572)
        MainWindow.setStyleSheet("background-color:rgb(170, 255, 255)\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, -20, 961, 71))
        self.label.setStyleSheet("background:rgb(170, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 201, 171))
        self.label_2.setStyleSheet("border: 3px solid rgb(12, 38, 127); /* Viền màu đỏ dày 3px */\n"
"border-radius: 9px;    /* Bo tròn góc */\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Pictures/12.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 40, 621, 171))
        self.label_3.setStyleSheet("border: 3px solid rgb(12, 38, 127); /* Viền màu xanh dương đậm */\n"
"border-radius: 10px;    /* Bo tròn góc */\n"
"background: rgb(85, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.btn_open_second = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_open_second.setGeometry(QtCore.QRect(720, 430, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(10)
        self.btn_open_second.setFont(font)
        self.btn_open_second.setStyleSheet("font: 87 italic 10pt \"Segoe UI Black\";\n"
"\n"
"background: rgb(85, 255, 255)")
        self.btn_open_second.setObjectName("btn_open_second")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 290, 581, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.input_ten = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.input_ten.setStyleSheet("border: 1px solid royalblack; /* Viền màu xanh dương đậm */\n"
"border-radius: 10px;    /* Bo tròn góc */\n"
"")
        self.input_ten.setObjectName("input_ten")
        self.verticalLayout_2.addWidget(self.input_ten)
        self.label_5 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.input_tuoi = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.input_tuoi.setStyleSheet("border: 1px solid royalblack; /* Viền màu xanh dương đậm */\n"
"border-radius: 10px;    /* Bo tròn góc */\n"
"")
        self.input_tuoi.setObjectName("input_tuoi")
        self.verticalLayout_2.addWidget(self.input_tuoi)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 220, 691, 61))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(720, 290, 171, 121))
        self.label_7.setStyleSheet("border: 3px solid rgb(12, 38, 127); /* Viền màu đỏ dày 3px */\n"
"border-radius: 9px;    /* Bo tròn góc */\n"
"")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../Pictures/13.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#0c267f;\">TƯ VẤN THUỐC TRỰC TUYẾN</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">💊 </span><span style=\" font-size:10pt; font-weight:600;\">Nền tảng tư vấn thuốc trực tuyến – Trợ lý sức khỏe thông minh!</span></p><p><span style=\" font-size:10pt;\">🔹 Nhập triệu chứng, nhận ngay gợi ý thuốc an toàn.<br/>🔹 Tư vấn nhanh, chính xác, 24/7 từ đội ngũ chuyên gia.<br/>🔹 Cập nhật thông tin thuốc đầy đủ, giúp bạn an tâm sử dụng.</span></p><p><span style=\" font-size:10pt;\">🚀 </span><span style=\" font-size:10pt; font-weight:600;\">Đơn giản – An toàn – Hiệu quả!</span><span style=\" font-size:10pt;\"> Trải nghiệm ngay! 💙</span></p></body></html>"))
        self.btn_open_second.setText(_translate("MainWindow", "Tư Vấn"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0c267f;\">Tên bệnh nhân :</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#0c267f;\">Tuổi:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#48006d;\">NHẬP THÔNG TIN TẠI ĐÂY ĐỂ ĐƯỢC TƯ VẤN NHA</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
