# Form implementation generated from reading ui file 'giaodiendexuatthuoc.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow3):
        MainWindow3.setObjectName("MainWindow3")
        MainWindow3.resize(775, 432)
        MainWindow3.setStyleSheet("background-color:rgb(170, 255, 255)\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow3)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result_thuoc = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.label_result_thuoc.setGeometry(QtCore.QRect(20, 70, 521, 151))
        self.label_result_thuoc.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid royalblack; /* Viền màu xanh dương đậm */\n"
"border-radius: 10px;    /* Bo tròn góc */")
        self.label_result_thuoc.setReadOnly(True)
        self.label_result_thuoc.setObjectName("label_result_thuoc")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(-40, 10, 441, 41))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 250, 121, 91))
        self.label.setStyleSheet("border: 3px solid rgb(12, 38, 127); /* Viền màu đỏ dày 3px */\n"
"border-radius: 9px;    /* Bo tròn góc */\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/15.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 250, 121, 91))
        self.label_2.setStyleSheet("border: 3px solid rgb(12, 38, 127); /* Viền màu đỏ dày 3px */\n"
"border-radius: 9px;    /* Bo tròn góc */\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Pictures/16.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 250, 121, 91))
        self.label_4.setStyleSheet("border: 3px solid rgb(12, 38, 127); /* Viền màu đỏ dày 3px */\n"
"border-radius: 9px;    /* Bo tròn góc */\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Pictures/17.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(630, 250, 101, 91))
        self.label_5.setStyleSheet("border: 3px solid rgb(12, 38, 127); /* Viền màu đỏ dày 3px */\n"
"border-radius: 9px;    /* Bo tròn góc */\n"
"")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Pictures/18.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 250, 111, 91))
        self.label_6.setStyleSheet("border: 3px solid rgb(12, 38, 127); /* Viền màu đỏ dày 3px */\n"
"border-radius: 9px;    /* Bo tròn góc */\n"
"")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../../Pictures/19.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(570, 71, 171, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_de_xuat = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_de_xuat.setEnabled(True)
        self.btn_de_xuat.setStyleSheet("font: 87 italic 10pt \"Segoe UI Black\";\n"
"\n"
"background: rgb(85, 255, 255)")
        self.btn_de_xuat.setObjectName("btn_de_xuat")
        self.verticalLayout.addWidget(self.btn_de_xuat)
        self.btn_open_fourth = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_open_fourth.setEnabled(True)
        self.btn_open_fourth.setStyleSheet("font: 87 italic 10pt \"Segoe UI Black\";\n"
"\n"
"background: rgb(85, 255, 255)")
        self.btn_open_fourth.setObjectName("btn_open_fourth")
        self.verticalLayout.addWidget(self.btn_open_fourth)
        self.btn_open_second = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_open_second.setEnabled(True)
        self.btn_open_second.setStyleSheet("font: 87 italic 10pt \"Segoe UI Black\";\n"
"\n"
"background: rgb(85, 255, 255)")
        self.btn_open_second.setObjectName("btn_open_second")
        self.verticalLayout.addWidget(self.btn_open_second)
        MainWindow3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 26))
        self.menubar.setObjectName("menubar")
        MainWindow3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow3)
        self.statusbar.setObjectName("statusbar")
        MainWindow3.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow3)

    def retranslateUi(self, MainWindow3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow3.setWindowTitle(_translate("MainWindow3", "MainWindow"))
        self.label_result_thuoc.setHtml(_translate("MainWindow3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow3", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:normal; color:#48006d;\">ĐỀ XUẤT THUỐC SỬ DỤNG</span></p></body></html>"))
        self.btn_de_xuat.setText(_translate("MainWindow3", "Đề xuất thuốc"))
        self.btn_open_fourth.setText(_translate("MainWindow3", "Lưu"))
        self.btn_open_second.setText(_translate("MainWindow3", "Quay Lại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow3 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow3)
    MainWindow3.show()
    sys.exit(app.exec())
